name: version bumper dev on push
on:
  push:
    branches:
      - dev-action
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: ${{ github.ref_name }}

    - name: bump-version-on-push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git fetch --tags
        tagFmt="^0.[0-9]+\.[0-9]+$"
        tag="$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "$tagFmt" | head -n 1)"
        [[ "$tag" =~ ^0.([0-9]+)\.([0-9]+) ]]
        minor=${BASH_REMATCH[1]}
        git tag -f "0.$(($minor+1)).0"
        git push -f origin "0.$(($minor+1)).0"
